### ISSUE TITLE
Can't get cask_versions working

### ISSUE THREAD

**Issue by christopherdwhite** [kitchenplan/kitchenplan#113]
I'm trying to install a couple of applications via the [Homebrew Cask versions tap](https://github.com/caskroom/homebrew-versions) and I'm having trouble getting it to work. 

On a past configuration I was able to include this in my configuration:

```yml
cask_versions:
            # Vector Editors
            - sketch-beta
            # Text Editors & IDEs
            - sublime-text-dev
```

When I do that now it doesn't seem to give me any errors but none of the apps are installed.

The tap seems to work:

```bash
  * execute[tapping caskroom/cask] action run
    - execute sudo -u cwhite /usr/local/bin/brew tap caskroom/cask
  * homebrewalt_tap[caskroom/versions] action tap
  
  * execute[tapping caskroom/versions] action run
    - execute sudo -u cwhite /usr/local/bin/brew tap caskroom/versions
  * homebrewalt_tap[caskroom/fonts] action tap
  
  * execute[tapping caskroom/fonts] action run
    - execute sudo -u cwhite /usr/local/bin/brew tap caskroom/fonts
  * homebrewalt_tap[homebrew/dupes] action tap
```

Cask fonts work as expected.

```yml
        cask_fonts:
            # Anonymous Pro
            - anonymous-pro
```

I can't remember doing anything special in my previous configuration to get cask_versions working. Any ideas what I'm missing or doing wrong?

Thanks!

**Comment by roderik** [comment]
There is no `cask_versions` array, just put them in `cask_apps`. There is just a special array for fonts because we manually add the `font-`prefix to make it a bit more clean.

**Comment by christopherdwhite** [comment]
Of course, that makes sense. Thanks @roderik, that worked perfectly!
