### ISSUE TITLE
What is the best way to use unreleased recipes?

### ISSUE THREAD

**Issue by grettke** [kitchenplan/kitchenplan#116]
Good evening,

I would like to use two recipes

https://github.com/kitchenplan/chef-osxdefaults/blob/master/recipes/use_dark_menu_bar_and_dock.rb

https://github.com/kitchenplan/chef-osxdefaults/blob/master/recipes/dock_wipe_all_default_app_icons_from_dock.rb

that are not out yet with the Gem bundle.

What is the "right way" start using them now?

Alternately, when would the next Gem bundle go out with these guys in them?

These recipes are already old, and I why I didn't get them when I installed Kitchenplan. Perhaps I was doing something wrong? I just followed the directions and nothing more.

Kind regards,

gcr

**Comment by roderik** [comment]
Remove the versioning in your own config repo, like this: https://github.com/roderik/kitchenplan-config/blob/master/Cheffile.This way you get the master version of the cookbooks.

This is also the way to add other cookbooks should you need or want them.

Nevertheless I will tag new cookbook versions soon.

**Comment by grettke** [comment]
Thank you sir, will do.

**Comment by grettke** [comment]
Done, thank you.
