### ISSUE TITLE
How to cleanly remove kitchenplan?

### ISSUE THREAD

**Issue by bschlief** [kitchenplan/kitchenplan#117]
I've used Boxen before, and one thing they've got which is really neat is a nuke script to clean everything boxen installed.

Is there a way to do that with kitchen plan yet?

I <3 this project. Thanks for all the hard work.

**Comment by roderik** [comment]
No, Kitchenplan doesn't have a nuke script. 

To be able to do this, boxen does a lot of very specific stuff to install everything in custom boxen locations. So your ruby and gems are in a special location, etc etc. I worked with Boxen before starting Kitchenplan and these custom things made some stuff a lot harder than it should be.

Kitchenplan is made specifically that the end result after running it, is the same as if you would install all the things by hand. Think of it as if you would delete /opt/kitchenplan that you can't see a difference between a kitchenplanned computer and a computer installed by hand. This also means that if there are errors, or something doesn't work the way you want, everything you find online is relevant. This is also the reason we depend heavily on homebrew and homebrew cask, these are huge communities that keep everything up to date, while the kitchenplan "shell" is just a little configuration and some settings.

**Comment by bschlief** [comment]
Oh, great explanation. Thanks for that! I'll submit a PR for a FAQ with this content in it.

**Comment by bschlief** [comment]
Answered and closing!
